///////////////////////////////////////////////////////////////////////////////
///
/// Copyright (c) 2013 - <company name here>
///
/// Original filename: CRD.h
/// Project          : CRD
/// Date of creation : <see CRD.cpp>
/// Author(s)        : <see CRD.cpp>
///
/// Purpose          : <see CRD.cpp>
///
/// Revisions:         <see CRD.cpp>
///
///////////////////////////////////////////////////////////////////////////////

// $Id$

#ifndef __CRD_H_VERSION__
#define __CRD_H_VERSION__ 100

#if defined(_MSC_VER) && (_MSC_VER >= 1020)
#pragma once
#endif


#include "drvcommon.h"
#include "drvversion.h"

#define DEVICE_NAME			"\\Device\\dtsoftbus02"
#define SYMLINK_NAME		"\\DosDevices\\dtsoftbus02"
#define OPEN_SYMLINK_NAME		L"\\\\.\\dtsoftbus02"
#define DEVICE_FILE_NAME		L"dtsoftbus02"

#ifdef CONSOLEDLL_EXPORTS
#include "winioctl.h"
#else
PRESET_UNICODE_STRING(usDeviceName, DEVICE_NAME);
PRESET_UNICODE_STRING(usSymlinkName, SYMLINK_NAME);
#endif

#ifndef FILE_DEVICE_CRD
#define FILE_DEVICE_CRD 0x8000
#endif

// Values defined for "Method"
// METHOD_BUFFERED
// METHOD_IN_DIRECT
// METHOD_OUT_DIRECT
// METHOD_NEITHER
// 
// Values defined for "Access"
// FILE_ANY_ACCESS
// FILE_READ_ACCESS
// FILE_WRITE_ACCESS


#define IOCTL_CRD_OPERATION(i) CTL_CODE(FILE_DEVICE_CRD, FILE_DEVICE_CRD + i, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define IOCTL_CRD_OPERATION_TRANSFER IOCTL_CRD_OPERATION(0)

#define IOCTL_CRD_OPERATION_KERNELHOOK_CHECK IOCTL_CRD_OPERATION(1)

#define IOCTL_CRD_OPERATION_KERNELHOOK_GET IOCTL_CRD_OPERATION(2)

#define IOCTL_CRD_OPERATION_PROCESSES_LIST IOCTL_CRD_OPERATION(3)

#define IOCTL_CRD_OPERATION_PROCESSES_GET IOCTL_CRD_OPERATION(4)

#define IOCTL_CRD_OPERATION_MODULES_LIST IOCTL_CRD_OPERATION(5)

#define IOCTL_CRD_OPERATION_MODULES_GET IOCTL_CRD_OPERATION(6)

#define IOCTL_CRD_OPERATION_THREADS_LIST IOCTL_CRD_OPERATION(7)

#define IOCTL_CRD_OPERATION_THREADS_GET IOCTL_CRD_OPERATION(8)

#define IOCTL_CRD_OPERATION_MODULE_PE_INFO_GET IOCTL_CRD_OPERATION(9)

#define IOCTL_CRD_OPERATION_CR4_GET IOCTL_CRD_OPERATION(10)

#define IOCTL_CRD_OPERATION_READPROCESSMEMORY IOCTL_CRD_OPERATION(11)

#define IOCTL_CRD_OPERATION_WRITEPROCESSMEMORY IOCTL_CRD_OPERATION(12)

#define IOCTL_CRD_OPERATION_KERNEL_MODULES_LIST IOCTL_CRD_OPERATION(13)

#define IOCTL_CRD_OPERATION_KERNEL_MODULES_GET IOCTL_CRD_OPERATION(14)

#define IOCTL_CRD_OPERATION_KERNEL_SSDT_LIST IOCTL_CRD_OPERATION(15)

#define IOCTL_CRD_OPERATION_KERNEL_SSDT_GET IOCTL_CRD_OPERATION(16)

#define IOCTL_CRD_OPERATION_KERNEL_SSDTSHADOW_LIST IOCTL_CRD_OPERATION(17)

#define IOCTL_CRD_OPERATION_KERNEL_SSDTSHADOW_GET IOCTL_CRD_OPERATION(18)

#define IOCTL_CRD_OPERATION_KERNEL_DPCTIMER_LIST IOCTL_CRD_OPERATION(19)

#define IOCTL_CRD_OPERATION_KERNEL_DPCTIMER_GET IOCTL_CRD_OPERATION(20)

#define IOCTL_CRD_OPERATION_KERNEL_IOTIMER_LIST IOCTL_CRD_OPERATION(21)

#define IOCTL_CRD_OPERATION_KERNEL_IOTIMER_GET IOCTL_CRD_OPERATION(22)

#define IOCTL_CRD_OPERATION_SETLOGPATH IOCTL_CRD_OPERATION(23)

#define IOCTL_CRD_OPERATION_SYNCHRONIZA IOCTL_CRD_OPERATION(24)

#define IOCTL_CRD_OPERATION_GETSYNCHRONIZEINFO IOCTL_CRD_OPERATION(25)

#define IOCTL_CRD_OPERATION_SENDINPUT IOCTL_CRD_OPERATION(26)

#define IOCTL_CRD_OPERATION_FINDWINDOWEX IOCTL_CRD_OPERATION(28)

#define IOCTL_CRD_OPERATION_OPENPROCESS IOCTL_CRD_OPERATION(29)

#define IOCTL_CRD_OPERATION_GETPORT IOCTL_CRD_OPERATION(31)

#define IOCTL_CRD_OPERATION_SETPORT IOCTL_CRD_OPERATION(32)

#endif // __CRD_H_VERSION__
