#pragma once

enum SYSTEM_VERSION
{
	UNKNOWN = -1,
	WINDOWSXP = 0,
	WINDOWS2003 = 1,
	WINDOWSVISTA = 2,
	WINDOWS7 = 3,
	WINDOWS8 = 4
};

SYSTEM_VERSION GetSystemVersion();

typedef BOOL (WINAPI *LPFN_ISWOW64PROCESS) (HANDLE, PBOOL);

BOOL WINAPI IsWow64();